export enum Board {
    ONE = 1,
    TWO = 2,
    THREE = 3,
    FOUR = 4,
    FIVE = 5,
    SIX = 6,
    SEVEN = 7,
    HEIGHT = 8,
    NINE = 9,
    TEN = 10,
    ELEVEN = 11,
    TWELVE = 12,
    THIRTEEN = 13,
    FOURTEEN = 14,
    FIFTEEN = 15,
    SIXTEEN = 16,
    SEVENTEEN = 17,
    HEIGHTEEN = 18,
    NINETEEN = 19,
    TWENTY = 20,
    CENTER = 25,
    MISSED = 0,
}

export enum BoardZone {
    NORMAL = 1,
    TIMESTWO = 2,
    TIMESTHREE = 3,
}
